API_KEY = "PKCIW1M4P58EIQJW2T7E"
SECRET_KEY = "VzPuyA0Nvmq4xRJCWdJOzAA3jaRGpd9OnAdYWZUO"

ALPACA_CONFIG={
    "ALPACA_API_KEY ": "PKCIW1M4P58EIQJW2T7E",
    "ALPACA_SECRET_KEY": "VzPuyA0Nvmq4xRJCWdJOzAA3jaRGpd9OnAdYWZUO",
    "BASE_URL ":"https://paper-api.alpaca.markets"


}