# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(762, 685)
        font = QtGui.QFont()
        font.setFamily("HP Simplified Hans")
        font.setPointSize(9)
        mainWindow.setFont(font)
        mainWindow.setMouseTracking(True)
        mainWindow.setTabletTracking(False)
        mainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("stockicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(116, 235, 213, 255), stop:1 rgba(172, 182, 229, 255));")
        mainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 671, 201))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(2)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 360, 671, 201))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(2)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 85, 0);")
        self.menubar.setObjectName("menubar")
        self.menuStock = QtWidgets.QMenu(self.menubar)
        self.menuStock.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.menuStock.setObjectName("menuStock")
        self.menuScalping = QtWidgets.QMenu(self.menubar)
        self.menuScalping.setObjectName("menuScalping")
        self.menuRSI_Indexing = QtWidgets.QMenu(self.menubar)
        self.menuRSI_Indexing.setObjectName("menuRSI_Indexing")
        self.menuQuick_Recommendation = QtWidgets.QMenu(self.menubar)
        self.menuQuick_Recommendation.setObjectName("menuQuick_Recommendation")
        mainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuStock.menuAction())
        self.menubar.addAction(self.menuScalping.menuAction())
        self.menubar.addAction(self.menuRSI_Indexing.menuAction())
        self.menubar.addAction(self.menuQuick_Recommendation.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Trading Strategy Analyzer"))
        self.label.setText(_translate("mainWindow", "Welcome To \n"
"Trading Strategy Analyzer"))
        self.label_2.setText(_translate("mainWindow", "Please Choose One of the \n"
"Options to Get Started"))
        self.menuStock.setTitle(_translate("mainWindow", "Trend Following"))
        self.menuScalping.setTitle(_translate("mainWindow", "Scalping"))
        self.menuRSI_Indexing.setTitle(_translate("mainWindow", "RSI Indexing"))
        self.menuQuick_Recommendation.setTitle(_translate("mainWindow", "Quick Recommendation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
