# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def openRSI(self):
        self.window = QtWidgets.QMainWindow()
        from RSIWin import Ui_RSIWin
        self.ui = Ui_RSIWin()
        self.ui.setupUi(self.window)
        self.window.show()

    def openTrend(self):
        self.window = QtWidgets.QMainWindow()
        from TrendWin import Ui_TrendWin
        self.ui = Ui_TrendWin()
        self.ui.setupUi(self.window)
        self.window.show()

    def openScalping(self):
        self.window = QtWidgets.QMainWindow()
        from ScalpingWin import Ui_ScalpingWin
        self.ui = Ui_ScalpingWin()
        self.ui.setupUi(self.window)
        self.window.show()

    def openGeneral(self):
        self.window = QtWidgets.QMainWindow()
        from GRWin import Ui_GRWin
        self.ui = Ui_GRWin()
        self.ui.setupUi(self.window)
        self.window.show()

    def openHome(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_mainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(753, 685)
        font = QtGui.QFont()
        font.setFamily("HP Simplified Hans")
        font.setPointSize(9)
        mainWindow.setFont(font)
        mainWindow.setMouseTracking(True)
        mainWindow.setTabletTracking(False)
        mainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("stockicon.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(116, 235, 213, 255), stop:1 rgba(172, 182, 229, 255));")
        mainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 671, 201))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(2)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 360, 671, 201))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(2)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("background-color: rgb(116, 235, 213);")
        self.menubar.setObjectName("menubar")
        self.menuStock = QtWidgets.QMenu(self.menubar)
        self.menuStock.setStyleSheet("background-color: rgb(172, 182, 229);")
        self.menuStock.setObjectName("menuStock")
        self.menuScalping = QtWidgets.QMenu(self.menubar)
        self.menuScalping.setStyleSheet(
            "background-color: rgb(172, 182, 229);")
        self.menuScalping.setObjectName("menuScalping")
        mainWindow.setMenuBar(self.menubar)
        self.actionTrend_Following = QtWidgets.QAction(mainWindow)
        self.actionTrend_Following.setObjectName("actionTrend_Following")
        self.actionTrend_Following.triggered.connect(self.openTrend)
        self.actionTrend_Following.triggered.connect(mainWindow.close)
        self.actionScalping = QtWidgets.QAction(mainWindow)
        self.actionScalping.setObjectName("actionScalping")
        self.actionScalping.triggered.connect(self.openScalping)
        self.actionScalping.triggered.connect(mainWindow.close)
        self.actionRSI_Indexing = QtWidgets.QAction(mainWindow)
        self.actionRSI_Indexing.setObjectName("actionRSI_Indexing")
        self.actionRSI_Indexing.triggered.connect(self.openRSI)
        self.actionRSI_Indexing.triggered.connect(mainWindow.close)
        self.actionHome = QtWidgets.QAction(mainWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionHome.triggered.connect(self.openHome)
        self.actionHome.triggered.connect(mainWindow.close)
        self.actionGeneral_Recommendation = QtWidgets.QAction(mainWindow)
        self.actionGeneral_Recommendation.setObjectName(
            "actionGeneral_Recommendation")
        self.actionGeneral_Recommendation.triggered.connect(self.openGeneral)
        self.actionGeneral_Recommendation.triggered.connect(mainWindow.close)
        self.menuStock.addAction(self.actionTrend_Following)
        self.menuStock.addAction(self.actionScalping)
        self.menuStock.addAction(self.actionRSI_Indexing)
        self.menuScalping.addAction(self.actionHome)
        self.menuScalping.addAction(self.actionGeneral_Recommendation)
        self.menubar.addAction(self.menuStock.menuAction())
        self.menubar.addAction(self.menuScalping.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate(
            "mainWindow", "Trading Strategy Analyzer"))
        self.label.setText(_translate("mainWindow", "Welcome To \n"
                                      "Trading Strategy Analyzer"))
        self.label_2.setText(_translate("mainWindow", "Please Choose One of the \n"
                                        "Options to Get Started"))
        self.menuStock.setTitle(_translate("mainWindow", "Strategies"))
        self.menuScalping.setTitle(_translate("mainWindow", "Others"))
        self.actionTrend_Following.setText(
            _translate("mainWindow", "Trend Following"))
        self.actionScalping.setText(_translate("mainWindow", "Scalping"))
        self.actionRSI_Indexing.setText(
            _translate("mainWindow", "RSI Indexing"))
        self.actionHome.setText(_translate("mainWindow", "Home"))
        self.actionGeneral_Recommendation.setText(
            _translate("mainWindow", "General Recommendation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
