# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrendFollowing.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrendWin(object):
    def openRSI(self):
        self.window = QtWidgets.QMainWindow()
        from RSIWin import Ui_RSIWin
        self.ui = Ui_RSIWin()
        self.ui.setupUi(self.window)
        self.window.show()

    def openTrend(self):
        self.window = QtWidgets.QMainWindow()
        from TrendWin import Ui_TrendWin
        self.ui = Ui_TrendWin()
        self.ui.setupUi(self.window)
        self.window.show()

    def openScalping(self):
        self.window = QtWidgets.QMainWindow()
        from ScalpingWin import Ui_ScalpingWin
        self.ui = Ui_ScalpingWin()
        self.ui.setupUi(self.window)
        self.window.show()

    def openGeneral(self):
        self.window = QtWidgets.QMainWindow()
        from GRWin import Ui_GRWin
        self.ui = Ui_GRWin()
        self.ui.setupUi(self.window)
        self.window.show()

    def openHome(self):
        self.window = QtWidgets.QMainWindow()
        from gui import Ui_mainWindow
        self.ui = Ui_mainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, TrendWin):
        TrendWin.setObjectName("TrendWin")
        TrendWin.setEnabled(True)
        TrendWin.resize(900, 500)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TrendWin.sizePolicy().hasHeightForWidth())
        TrendWin.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("trend.jpg"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TrendWin.setWindowIcon(icon)
        TrendWin.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(TrendWin)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 80, 671, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(410, 410, 113, 22))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 40, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(490, 190, 111, 16))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(610, 190, 110, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 190, 111, 21))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(190, 300, 111, 21))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(310, 300, 113, 22))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 250, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 190, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(610, 250, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(490, 250, 101, 16))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 410, 81, 16))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 125, 381, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(490, 290, 161, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(410, 350, 93, 28))
        self.pushButton.setObjectName("pushButton")
        TrendWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrendWin)
        self.menubar.setStyleSheet(
            "background-color: rgb(116, 235, 213);")
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuStrategies = QtWidgets.QMenu(self.menubar)
        self.menuStrategies.setStyleSheet(
            "background-color: rgb(172, 182, 229);")
        self.menuStrategies.setObjectName("menuStrategies")
        self.menuOthers = QtWidgets.QMenu(self.menubar)
        self.menuOthers.setStyleSheet(
            "background-color: rgb(172, 182, 229);")
        self.menuOthers.setObjectName("menuOthers")
        TrendWin.setMenuBar(self.menubar)
        self.actionScapling = QtWidgets.QAction(TrendWin)
        self.actionScapling.setObjectName("actionScapling")
        self.actionRSI_Indexing = QtWidgets.QAction(TrendWin)
        self.actionRSI_Indexing.setObjectName("actionRSI_Indexing")
        self.actionGeneral_Recommendation = QtWidgets.QAction(TrendWin)
        self.actionGeneral_Recommendation.setObjectName(
            "actionGeneral_Recommendation")
        self.actionHome = QtWidgets.QAction(TrendWin)
        self.actionHome.setObjectName("actionHome")
        self.actionTrend_Following = QtWidgets.QAction(TrendWin)
        self.actionTrend_Following.setObjectName("actionTrend_Following")
        self.actionScalping = QtWidgets.QAction(TrendWin)
        self.actionScalping.setObjectName("actionScalping")
        self.actionScalping.triggered.connect(self.openScalping)
        self.actionScalping.triggered.connect(TrendWin.close)
        self.actionRSI = QtWidgets.QAction(TrendWin)
        self.actionRSI.setObjectName("actionRSI")
        self.actionRSI.triggered.connect(self.openRSI)
        self.actionRSI.triggered.connect(TrendWin.close)
        self.actionTrend_Following_2 = QtWidgets.QAction(TrendWin)
        self.actionTrend_Following_2.setObjectName("actionTrend_Following_2")
        self.actionTrend_Following_2.triggered.connect(self.openTrend)
        self.actionTrend_Following_2.triggered.connect(TrendWin.close)
        self.actionHome_2 = QtWidgets.QAction(TrendWin)
        self.actionHome_2.setObjectName("actionHome_2")
        self.actionHome_2.triggered.connect(self.openHome)
        self.actionHome_2.triggered.connect(TrendWin.close)
        self.actionGeneral_Recommendation_2 = QtWidgets.QAction(TrendWin)
        self.actionGeneral_Recommendation_2.setObjectName(
            "actionGeneral_Recommendation_2")
        self.actionGeneral_Recommendation_2.triggered.connect(self.openGeneral)
        self.actionGeneral_Recommendation_2.triggered.connect(TrendWin.close)
        self.menuStrategies.addAction(self.actionScalping)
        self.menuStrategies.addAction(self.actionRSI)
        self.menuStrategies.addAction(self.actionTrend_Following_2)
        self.menuOthers.addAction(self.actionHome_2)
        self.menuOthers.addAction(self.actionGeneral_Recommendation_2)
        self.menubar.addAction(self.menuStrategies.menuAction())
        self.menubar.addAction(self.menuOthers.menuAction())

        self.retranslateUi(TrendWin)
        QtCore.QMetaObject.connectSlotsByName(TrendWin)

    def retranslateUi(self, TrendWin):
        _translate = QtCore.QCoreApplication.translate
        TrendWin.setWindowTitle(_translate("TrendWin", "Trend Following"))
        self.label_5.setText(_translate("TrendWin", "Trend Following is the strategy of following is the idea of understanding \n"
                                        "price trends to determine when to enter and exit the market."))
        self.lineEdit_3.setPlaceholderText(_translate("TrendWin", "0"))
        self.label_4.setText(_translate("TrendWin", "Trend Following"))
        self.label_7.setText(_translate("TrendWin", "Start Date"))
        self.label.setText(_translate("TrendWin", "Stock Tag"))
        self.lineEdit_2.setPlaceholderText(_translate("TrendWin", "0"))
        self.label_8.setText(_translate("TrendWin", "End Date"))
        self.label_9.setText(_translate("TrendWin", "Start Hour"))
        self.label_2.setText(_translate("TrendWin", "Buy/Sell \n"
                                        "Percentage"))
        self.label_3.setText(_translate("TrendWin", "Win Rate"))
        self.label_6.setText(_translate("TrendWin", "Dates need to be from LAST 30 DAYS\n"
                                        "If choosing one day, END DATE would be the NEXT DAY\n Win Rate presented only with RANGE OF DAYS "))
        self.checkBox.setText(_translate("TrendWin", "Range of Days"))
        self.pushButton.setText(_translate("TrendWin", "Submit"))
        self.menuStrategies.setTitle(_translate("TrendWin", "Strategies"))
        self.menuOthers.setTitle(_translate("TrendWin", "Others"))
        self.actionScapling.setText(_translate("TrendWin", "Scalping"))
        self.actionRSI_Indexing.setText(_translate("TrendWin", "RSI Indexing"))
        self.actionGeneral_Recommendation.setText(
            _translate("TrendWin", "General Recommendation"))
        self.actionHome.setText(_translate("TrendWin", "Home"))
        self.actionTrend_Following.setText(
            _translate("TrendWin", "Trend Following"))
        self.actionScalping.setText(_translate("TrendWin", "Scalping"))
        self.actionRSI.setText(_translate("TrendWin", "RSI Indexing"))
        self.actionTrend_Following_2.setText(
            _translate("TrendWin", "Trend Following"))
        self.actionHome_2.setText(_translate("TrendWin", "Home"))
        self.actionGeneral_Recommendation_2.setText(
            _translate("TrendWin", "General Recommendation"))

    def trendOutput(self):
        import sys
        import os
        current = os.path.dirname(os.path.realpath(__file__))
        parent = os.path.dirname(current)
        sys.path.append(parent)
        from Strategies.general import convertDate
        from Strategies.trendFollowing import rangeTrendFollowing, oneDayData, graphTrendOneDay, trendFollowing
        stock = self.lineEdit.text()
        buyPSellP = self.lineEdit_2.text()
        startDate = self.dateEdit_2.text()
        endDate = self.dateEdit.text()
        startD, endD = convertDate(startDate, endDate)
        rangeChecked = self.checkBox.isChecked()
        starthour = self.lineEdit_4.text()

        if rangeChecked:
            profitsTrend, winRateTrend = rangeTrendFollowing(
                stock, startD, endD, buyPSellP, buyPSellP, starthour)
            self.lineEdit_4.setText(str(winRateTrend) + "%")
        else:
            dataTrend = oneDayData(stock, startD, endD)
            buy, sell, profits = trendFollowing(
                dataTrend, buyPSellP, buyPSellP, starthour)
            graphTrendOneDay(buy, sell, dataTrend)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrendWin = QtWidgets.QMainWindow()
    ui = Ui_TrendWin()
    ui.setupUi(TrendWin)
    TrendWin.show()
    sys.exit(app.exec_())
